num1 = int(input())
num2 = int(input())
print(f"{num1} + {num2} = {num1+num2}")
print(num1, "+", num2,"=", num1+num2)
print("{} + {} = {}".format(num1, num2, num1+num2))
print("%d + %d = %d"%(num1, num2, num1+num2))